// envelope prints the objects of the hub policy's workload ConfigurationPolicies as plain
// manifests, for clusters without ACM (the 2026-prod-1 CI target). The dashboards template is
// left out: its ConfigMaps live in the ACM Observability namespace.
//
//	go run ./hack/envelope deploy/acm/policy-hub-fleet-validator.yaml > envelope.yaml
package main

import (
	"fmt"
	"os"

	"sigs.k8s.io/yaml"
)

var workloadPolicies = map[string]bool{
	"hub-fleet-validator-config":     true,
	"hub-fleet-validator-monitoring": true,
}

func main() {
	if len(os.Args) != 2 {
		fmt.Fprintln(os.Stderr, "usage: envelope <rendered-policy.yaml>")
		os.Exit(2)
	}
	if err := run(os.Args[1]); err != nil {
		fmt.Fprintln(os.Stderr, "envelope:", err)
		os.Exit(1)
	}
}

func run(path string) error {
	b, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	var policy map[string]any
	if err := yaml.Unmarshal(b, &policy); err != nil {
		return fmt.Errorf("parse %s: %w", path, err)
	}
	spec, _ := policy["spec"].(map[string]any)
	templates, _ := spec["policy-templates"].([]any)

	fmt.Printf("# GENERATED by hack/envelope from %s — plain manifests for clusters without ACM.\n", path)
	n := 0
	for _, t := range templates {
		cp := nested(t, "objectDefinition")
		if !workloadPolicies[str(nested(cp, "metadata"), "name")] {
			continue
		}
		objs, _ := nested(cp, "spec")["object-templates"].([]any)
		for _, o := range objs {
			out, err := yaml.Marshal(nested(o, "objectDefinition"))
			if err != nil {
				return err
			}
			if n > 0 {
				fmt.Println("---")
			}
			fmt.Print(string(out))
			n++
		}
	}
	if n == 0 {
		return fmt.Errorf("no objects found in %s", path)
	}
	return nil
}

func nested(v any, key string) map[string]any {
	m, _ := v.(map[string]any)
	r, _ := m[key].(map[string]any)
	return r
}

func str(m map[string]any, key string) string {
	s, _ := m[key].(string)
	return s
}
