#!/usr/bin/env bash
# Wrap both dashboard JSONs in the ConfigMaps the MCO grafana-dashboard-loader picks up
# (for applying without the policy).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "${ROOT}"

FOLDER="${FOLDER:-Fleet-validator}"
OUT="deploy/grafana/fleet-validator-dashboards-configmap.yaml"

{
  echo "# GENERATED by hack/render-grafana-configmap.sh — do not edit; edit hack/gen-dashboards.py."
  first=1
  for name in acm-hub-validation-dashboard managed-cluster-validation-dashboard; do
    [[ ${first} -eq 1 ]] || echo "---"
    first=0
    cat <<EOF
apiVersion: v1
kind: ConfigMap
metadata:
  name: ${name}
  namespace: open-cluster-management-observability
  labels:
    grafana-custom-dashboard: "true"
  annotations:
    observability.open-cluster-management.io/dashboard-folder: ${FOLDER}
data:
  ${name}.json: |-
EOF
    sed 's/^/    /' "deploy/grafana/${name}.json"
  done
} > "${OUT}"

echo "rendered ${OUT} (folder ${FOLDER})"
