#!/usr/bin/env bash
# Render deploy/acm/policy-hub-fleet-validator.yaml from its template: pins the image to
# VERSION (default: v$(cat .localbuild)), embeds the MCO metrics allowlist and both dashboards.
#   IMAGE=... OUT=... ./hack/render-acm-policy.sh   (CI uses this for the GitOps bundle)
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "${ROOT}"

VERSION="${VERSION:-v$(tr -d '[:space:]' < .localbuild)}"
IMAGE="${IMAGE:-ghcr.io/dasmlab/fleet-validator:${VERSION}}"
TMPL="deploy/acm/policy-hub-fleet-validator.tmpl.yaml"
DASH_HUB="deploy/grafana/acm-hub-validation-dashboard.json"
DASH_MANAGED="deploy/grafana/managed-cluster-validation-dashboard.json"
OUT="${OUT:-deploy/acm/policy-hub-fleet-validator.yaml}"

METRICS="$(go run ./cmd/fleet-validator --print-metric-names)"

{
  echo "# GENERATED by hack/render-acm-policy.sh — do not edit; edit ${TMPL}."
  while IFS= read -r line; do
    case "${line}" in
      __ALLOWLIST__)
        while IFS= read -r m; do printf '                      - %s\n' "${m}"; done <<< "${METRICS}" ;;
      __DASHBOARD_HUB__)
        sed 's/^/                    /' "${DASH_HUB}" ;;
      __DASHBOARD_MANAGED__)
        sed 's/^/                    /' "${DASH_MANAGED}" ;;
      *)
        printf '%s\n' "${line//__IMAGE__/${IMAGE}}" ;;
    esac
  done < "${TMPL}"
} > "${OUT}"

echo "rendered ${OUT} (image ${IMAGE})" >&2
